export const MENU_REPOSITORES = [
  {
    id: 1,
    title: "hi-SPEC",
    description: "",
    image: "/images/hi-spec/hi-spec-page.png",
    tech_stacks: [
      "React.js",
      "TypeScript",
      "TailwindCSS",
      "React Router",
      "React Hook Form",
      "Axios",
      "Vite",
    ],
  },
  {
    id: 2,
    title: "cloudbite",
    description: "",
    image: "/images/cloudbite/cloudbite-page.png",
    tech_stacks: [
      "React.js",
      "TypeScript",
      "TailwindCSS",
      "React Router",
      "React Hook Form",
      "Axios",
      "Vite",
    ],
  },
  {
    id: 3,
    title: "sinau-apps",
    description: "",
    image: "/images/sinau-apps/Slide1.JPG",
    tech_stacks: ["Flutter", "Dart"],
  },
  {
    id: 4,
    title: "byek-movies",
    description: "",
    image: "/images/byek-movies/byek-movies-page.png",
    tech_stacks: [
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "React Query",
      "Axios",
    ],
  },
  {
    id: 5,
    title: "pokedex-app",
    description: "",
    image: "/images/pokedex-app/pokemon-page.png",
    tech_stacks: [
      "React.js",
      "TypeScript",
      "TailwindCSS",
      "React Router",
      "Axios",
      "Vite",
    ],
  },
];
